apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 065199070014.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 065199070014.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 92104d62
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
