---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-flask-backend
  namespace: default
  labels:
    tags.datadoghq.com/env: demo
    tags.datadoghq.com/service: "flask-demo"
    tags.datadoghq.com/version: "1.2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-flask-backend
  template:
    metadata:
      labels:
        app: demo-flask-backend
        tags.datadoghq.com/env: demo
        tags.datadoghq.com/service: "flask-demo"
        tags.datadoghq.com/version: "1.2"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/python-lib.version: v3.5.1
    spec:
      containers:
        - name: demo-flask-backend
          image: 065199070014.dkr.ecr.ap-northeast-2.amazonaws.com/demo-flask-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_SAMPLE_RATE
              value: "1"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_APPSEC_ENABLED
              value: "true"
            - name: DD_IAST_ENABLED
              value: "true"
            - name: DD_APPSEC_SCA_ENABLED
              value: "true"
            - name: DD_DYNAMIC_INSTRUMENTATION_ENABLED
              value: "true"
            - name: DD_GIT_COMMIT_SHA
              value: "18b7f53c9f59d6ff7093a1ed6e8d68c02b3d2d06"
            - name: DD_GIT_REPOSITORY_URL
              value: "https://github.com/SangkiJung/backend-flask-repo"
            - name: DD_SYMBOL_DATABASE_UPLOAD_ENABLED
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"